import { Question } from "../components/types";

export const SEED_QUESTIONS: Question[] = [
  {
    id: "q1",
    title: "How do I solve integration by parts in calculus?",
    body: "I keep making mistakes with the LIATE rule. Can someone walk through a clear example like integral of x * e^x step by step?",
    author: "Rahul Sharma",
    authorId: "u1",
    authorName: "Rahul Sharma",
    college: "Delhi University",
    subject: "Mathematics",
    tags: ["Calculus", "Integration"],
    votes: 14,
    answers: 2,
    createdAt: "2h ago",
    answersList: [
      {
        id: "a1",
        author: "Priya Mehta",
        authorId: "u2",
        authorName: "Priya Mehta",
        college: "IIT Delhi",
        isAccepted: true,
        votes: 9,
        createdAt: "1h ago",
        body: "Use integration by parts with u = x and dv = e^x dx. Then du = dx and v = e^x, so the answer becomes x e^x - e^x + C.",
      },
      {
        id: "a2",
        author: "Arjun Patel",
        authorId: "u3",
        authorName: "Arjun Patel",
        college: "NSIT",
        isAccepted: false,
        votes: 4,
        createdAt: "30m ago",
        body: "Think of it as the reverse product rule. Practice with x sin x and ln x after this one.",
      },
    ],
  },
  {
    id: "q2",
    title: "TCP vs UDP: when do you use each?",
    body: "My networking exam asks for practical scenarios. What real-world applications prefer UDP over TCP and why?",
    author: "Priya Mehta",
    authorId: "u2",
    authorName: "Priya Mehta",
    college: "IIT Delhi",
    subject: "Computer Networks",
    tags: ["TCP", "UDP", "Networking"],
    votes: 26,
    answers: 1,
    createdAt: "4h ago",
    answersList: [
      {
        id: "a3",
        author: "Sneha Roy",
        authorId: "u4",
        authorName: "Sneha Roy",
        college: "NIT Trichy",
        isAccepted: true,
        votes: 17,
        createdAt: "3h ago",
        body: "TCP is reliable and ordered, so use it for web, email, and file transfer. UDP is faster and works well for gaming, DNS, and live streaming where low latency matters more than retries.",
      },
    ],
  },
  {
    id: "q3",
    title: "Best roadmap for DSA preparation before placements?",
    body: "I am in 2nd year CSE and want to start competitive programming seriously. What order should I learn topics, and which platforms?",
    author: "Arjun Patel",
    authorId: "u3",
    authorName: "Arjun Patel",
    college: "NSIT",
    subject: "Data Structures",
    tags: ["DSA", "Placements", "Algorithms"],
    votes: 41,
    answers: 1,
    createdAt: "1d ago",
    answersList: [
      {
        id: "a4",
        author: "Karan Singh",
        authorId: "u5",
        authorName: "Karan Singh",
        college: "BITS Pilani",
        isAccepted: false,
        votes: 24,
        createdAt: "20h ago",
        body: "A good order is arrays, strings, hashing, two pointers, sliding window, stack, queue, binary search, trees, graphs, and finally dynamic programming.",
      },
    ],
  },
  {
    id: "q4",
    title: "Explain Kirchhoff's Voltage Law with a worked example",
    body: "I understand KVL in theory but keep getting wrong signs in multi-loop circuits. Can someone show a full worked example?",
    author: "Sneha Roy",
    authorId: "u4",
    authorName: "Sneha Roy",
    college: "NIT Trichy",
    subject: "Electrical Engineering",
    tags: ["KVL", "Circuits"],
    votes: 8,
    answers: 0,
    createdAt: "2d ago",
    answersList: [],
  },
  {
    id: "q5",
    title: "Process vs Thread: memory sharing and when to use each?",
    body: "I get confused about when context-switching costs make threads worse than processes. Looking for a practical mental model.",
    author: "Meera Iyer",
    authorId: "u6",
    authorName: "Meera Iyer",
    college: "IIT Bombay",
    subject: "Computer Science",
    tags: ["OS", "Concurrency"],
    votes: 31,
    answers: 1,
    createdAt: "3d ago",
    answersList: [
      {
        id: "a5",
        author: "Rahul Sharma",
        authorId: "u1",
        authorName: "Rahul Sharma",
        college: "Delhi University",
        isAccepted: true,
        votes: 20,
        createdAt: "2d ago",
        body: "Processes have separate memory and stronger isolation. Threads share memory and are lighter, so they are better when one app needs concurrent work with shared state.",
      },
    ],
  },
];
